name: CI

on:
  push:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1) Auth to GCP via Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/498855991921/locations/global/workloadIdentityPools/github-pool/providers/github-actions-provider"
          service_account: "terraform-user@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"

      # 2) Configure gcloud (optional, if you want to build/push images with gcloud)
      - name: Set gcloud project
        run: gcloud config set project $PROJECT_ID

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/$PROJECT_ID/terraform-demo:latest .

      - name: Push Docker image
        run: docker push gcr.io/$PROJECT_ID/terraform-demo:latest

      # 3) Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init/Plan/Apply
        working-directory: ./infra
        run: |
          terraform init
          terraform plan -var="project_id=$PROJECT_ID" -var="region=us-central1"
          terraform apply -auto-approve -var="project_id=$PROJECT_ID" -var="region=us-central1"
