name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: us # Artifact Registry region
      REPO_NAME: gcr-repo # Your Artifact Registry repository name

    permissions:
      id-token: write # required for Workload Identity Federation
      contents: read # needed to read the repo code

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1️⃣ Authenticate to Google Cloud via Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/498855991921/locations/global/workloadIdentityPools/github-pool/providers/github-actions-provider"
          service_account: "terraform-user@${{ env.PROJECT_ID }}.iam.gserviceaccount.com"

      # 2️⃣ Set GCP project
      - name: Set gcloud project
        run: gcloud config set project $PROJECT_ID

      # 3️⃣ Authenticate Docker with Artifact Registry
      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev

      - name: Debug Authentication
        run: |
          gcloud auth list
          gcloud projects list
          gcloud iam service-accounts describe terraform-user@authentic-wharf-452312-u7.iam.gserviceaccount.com

      # 4️⃣ Build and Push Docker Image to Artifact Registry
      - name: Build Docker image
        run: docker build -t us-docker.pkg.dev/authentic-wharf-452312-u7/gcr-repo/terraform-demo:latest ./app

      - name: Push Docker image
        run: docker push us-docker.pkg.dev/authentic-wharf-452312-u7/gcr-repo/terraform-demo:latest

      # 5️⃣ Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # 6️⃣ Run Terraform Init, Plan, and Apply
      - name: Terraform Init/Plan/Apply
        working-directory: ./infra
        run: |
          terraform init
          terraform plan -var="project_id=$PROJECT_ID" -var="region=$REGION"
          terraform apply -auto-approve -var="project_id=$PROJECT_ID" -var="region=$REGION"
